import { IonPerson as Avatar } from './avatar'
import { IcRoundHome as Home } from './home'
import { ZondiconsLockClosed as Lock } from './lock'
import { MdiMailRu as Email } from './email'
import { LetsIconsViewFill as EyeOpen } from './eye-open'
import { LetsIconsViewHideFill as EyeClosed } from './eye-closed'
import { Login } from './login'
import { Logout } from './logout'
import { Trash } from './trash'
import { Save } from './save'
import { New } from './new'
import { FolderNew } from './folder-new'
import { Folder } from './folder'
import { NewNote } from './new-note'
import { Close } from './close'
import { Check } from './check'
import { CiFolderOpen as FolderOpen } from './folder-open'

export { Avatar, Home, Lock, Email, EyeOpen, EyeClosed, Login, Logout, Trash, Save, New, FolderNew, Folder, NewNote, Close, Check, FolderOpen }
