import type { Metadata } from 'next'
import { cn } from '@/lib/cn'
import { inter, caveat, dmSans } from '@/fonts'
import './globals.css'

export const metadata: Metadata = {
 title: 'Create Next App',
 description: 'Generated by create next app',
}

export default function RootLayout({
 children,
}: Readonly<{
 children: React.ReactNode
}>) {
 return (
  <html lang='en'>
   <body className={cn(inter.variable, caveat.variable, dmSans.variable, 'font-dmSans')}>{children}</body>
  </html>
 )
}
