import type { Metadata } from 'next'
import { cn } from '@/lib'
import { inter, caveat, dmSans, sono } from '@/fonts'
import 'react-tooltip/dist/react-tooltip.css'
import './globals.css'

export const metadata: Metadata = {
 title: 'Create Next App',
 description: 'Generated by create next app',
}

export default function RootLayout({
 children,
}: Readonly<{
 children: React.ReactNode
}>) {
 return (
  <html lang='en'>
   <body className={cn(inter.variable, caveat.variable, dmSans.variable, sono.variable, 'font-dmSans overflow-hidden')}>{children}</body>
  </html>
 )
}
